version: "3.7"

services:
  users:
    container_name: users
    build:
      context: .
      args:
        - APP_ENV=dev
      dockerfile: ./deployment/Dockerfile
    command: uvicorn main:app --reload --host 0.0.0.0 --port 9000
    env_file:
      - .env
    volumes:
      - ./src:/app:cached
    ports:
      - 9000:9000
    stdin_open: true
    tty: true
    depends_on:
      - postgres-users

  postgres-users:
    image: postgres:14-alpine
    container_name: postgres-users
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5444:5432"
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
