"""add associations

Revision ID: 2510596b7f4d
Revises: fa0c9db5d164
Create Date: 2023-12-05 23:46:27.068932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2510596b7f4d'
down_revision = 'fa0c9db5d164'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_role_association',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.drop_table('user_role')
    op.alter_column('role_permission', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('role_permission', 'permission_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role_permission', 'permission_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('role_permission', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('user_role',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name='user_role_role_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_role_user_id_fkey')
    )
    op.drop_table('user_role_association')
    # ### end Alembic commands ###
